Add ESP8685-WROOM-06 schematic symbol and footprint
espressif/kicad-libraries pull request #148
Opened 2024-02-16 18:56 UTC by tbeckley

Had to create this for a project so here's some good citizenry. Also update README to add missing ESP8685-WROOM parts.

Hope I got all the tiny little dimensions right.

2024-02-26 14:44 UTC, pedrominatel requested changes
Hi @tbeckley, thank you for your contribution.
Can you check the following items?

- Check the thermal pad measurements (see picture)
- Move the coordinate origins to the center of the shield (close to x 7.9 and y -10)
![Screenshot 2024-02-26 at 14 41 33](https://github.com/espressif/kicad-libraries/assets/274658/4730a2fd-75f3-4a06-a289-0df1c5d7277e)

2024-02-26 19:08 UTC, tbeckley commented
Thanks for the review! I knew those stacked dimensions would get me. I have made the changes as requested.

2024-02-27 15:56 UTC, pedrominatel commented
Thank you, @tbeckley.
I've changed some things on this footprint. Please take a look.

![Screenshot 2024-02-27 at 15 48 47](https://github.com/espressif/kicad-libraries/assets/274658/9fba1cb6-b4fe-4114-a18a-90a92f6adb13)

2024-02-27 16:42 UTC, pedrominatel approved these changes

2024-02-27 18:03 UTC, merged