Add symbol and footprint for ESP32-DevKitM-1
espressif/kicad-libraries pull request #163
Opened 2024-03-04 16:15 UTC by veprbl

<img width="662" alt="image" src="https://github.com/espressif/kicad-libraries/assets/245573/6af14079-e8e8-4d4f-9e8e-7e23b0cfa088"><img width="317" alt="image" src="https://github.com/espressif/kicad-libraries/assets/245573/f819b200-9c0c-4a90-8d7e-4534d4965f30">

2024-04-12 12:58 UTC, pedrominatel requested changes

2024-04-12 12:58 UTC, pedrominatel commented on symbols/Espressif.kicad_sym
> +        (name "U0RXD/GPIO3" (effects (font (size 1.27 1.27))))
There is an inconsistency in our docs.
Please change the pins:

- Pin 32 is U0TX/GPIO1
- Pin 33 is U0RX/GPIO3

The official Espressif documentation will be updated/fixed.

2024-04-14 23:00 UTC, veprbl commented
<img width="634" alt="image" src="https://github.com/espressif/kicad-libraries/assets/245573/288ee144-c71b-4494-869c-4ec64be442f0">
<img width="295" alt="image" src="https://github.com/espressif/kicad-libraries/assets/245573/ea5bb731-c6d4-4412-93a3-b6ab4c25ce32">

2024-04-15 08:18 UTC, pedrominatel approved these changes
LGTM

2024-04-15 08:19 UTC, merged