ESP32-S2-DevKitM
espressif/kicad-libraries pull request #37
Opened 2022-03-19 00:14 UTC by mulcmu

Added symbol and footprint for the [ESP32-S2-DevKitM](https://docs.espressif.com/projects/esp-idf/en/latest/esp32s2/hw-reference/esp32s2/user-guide-devkitm-1-v1.html) dev board.  

Updated readme.

![ESP32-S2-DevKitM](https://user-images.githubusercontent.com/10102873/159098769-4ab9b9d3-2dc6-4a2b-9529-955faa61a1c5.png)
![symbol](https://user-images.githubusercontent.com/10102873/159098771-90410300-57a3-4bc0-bad9-b0ba9345efc6.png)
.

2022-03-21 22:14 UTC, mulcmu commented
I think it is complete.   I double checked it again and made two small tweaks to pad shapes in 8ae8101.

2022-03-22 10:22 UTC, pedrominatel commented
Thanks for your contribution @mulcmu!

I'll prepare the review and merge it ASAP!

2022-03-22 12:12 UTC, pedrominatel commented on footprints/Espressif.pretty/ESP32-S2-DevKitM.kicad_mod
> +  (fp_text user "GPIO19" (at 17.662619 48.25728 unlocked) (layer "B.SilkS")
Consider adding the D- to the silkscreen.

2022-03-22 12:12 UTC, pedrominatel commented on footprints/Espressif.pretty/ESP32-S2-DevKitM.kicad_mod
> +  (fp_text user "GPIO20" (at 17.662619 45.71728 unlocked) (layer "B.SilkS")
Consider adding the D+ to the silkscreen.

2022-03-22 12:14 UTC, pedrominatel requested changes
Looks good to me!
Please consider the changes I've suggested and try to keep only GND with the rectangle pad shape.

Thanks!

2022-03-22 23:39 UTC, mulcmu commented
All the review comments were addressed in fa376b7

2022-03-23 08:41 UTC, pedrominatel approved these changes
LGTM!

2022-03-23 08:42 UTC, merged